/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D2A
 */
public class formbarang extends javax.swing.JFrame {

    /**
     * Creates new form formbarang
     */
    public formbarang() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        xkdbrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        xnmbrg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        xsatbrg = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        xjmlbrg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        xhrgbrg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("Entry Data Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 669, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Kode Barang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 9, -1, -1));

        xkdbrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xkdbrgKeyPressed(evt);
            }
        });
        jPanel2.add(xkdbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 6, 160, -1));

        jLabel3.setText("Nama Barang");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 37, -1, -1));

        xnmbrg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xnmbrgFocusGained(evt);
            }
        });
        jPanel2.add(xnmbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 34, 271, -1));

        jLabel4.setText("Satuan");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 65, -1, -1));

        xsatbrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilo", "Meter", "Lusin", "Gross", "Botol", "Liter", "Kilo", "Doz", "Pcs", "Sacet", " " }));
        xsatbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsatbrgActionPerformed(evt);
            }
        });
        jPanel2.add(xsatbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 62, 104, -1));

        jLabel5.setText("Jumlah");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 93, -1, -1));
        jPanel2.add(xjmlbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 90, 104, -1));

        jLabel6.setText("Harga");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 121, -1, -1));
        jPanel2.add(xhrgbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 118, 104, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 669, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 189, 669, 207));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnew.setText("New");
        jPanel3.add(btnnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 85, 36));

        btnsave.setText("Save");
        jPanel3.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 6, 84, 36));

        btnupdate.setText("Update");
        jPanel3.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 6, -1, 36));

        btndelete.setText("Delete");
        jPanel3.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 6, 84, 36));

        btnprint.setText("Print");
        jPanel3.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 6, 83, 36));

        btnexit.setText("Exit");
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        jPanel3.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 6, 81, 36));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 402, -1, 52));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        
        int pilih=JOptionPane.showConfirmDialog(null,
                "Yakin Keluar ?","Perhatian !",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (pilih==0)
        {
             System.exit(0);
        }
       
    }//GEN-LAST:event_btnexitMouseClicked

    private void table(){
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("id");
    tbl.addColumn("Nama Barang");
    tbl.addColumn("Satuan");
    tbl.addColumn("jumlah");
    tbl.addColumn("harga");
        
    try{
        Statement stm =(Statement) KoneksiDb.getConn().createStatement();
        ResultSet rs =stm.executeQuery("SELECT * FROM tb_toko");
       while (rs.next()) {
           tbl.addRow(new Object[]{
           rs.getInt("id"),
           rs.getString("nama"),
               rs.getString("satuan"),
               rs.getInt("jumlah"),
                rs.getInt("harga")
               
           });
            jTable1.setModel(tbl);
       }
       
        JOptionPane.showMessageDialog(null,"koneksi database berhasil");
    }
    catch(Exception e){
                JOptionPane.showMessageDialog(null,"koneksi database gagal" + e.getMessage());

    }
    
    }
    private void xkdbrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xkdbrgKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            xnmbrg.requestFocus();
        }
    }//GEN-LAST:event_xkdbrgKeyPressed

    private void xnmbrgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xnmbrgFocusGained
        // TODO add your handling code here:
        if (xkdbrg.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "KOde Barang Masih Kosong !");
            xkdbrg.requestFocus();
        }
    }//GEN-LAST:event_xnmbrgFocusGained

    private void xsatbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsatbrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xsatbrgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField xhrgbrg;
    private javax.swing.JTextField xjmlbrg;
    private javax.swing.JTextField xkdbrg;
    private javax.swing.JTextField xnmbrg;
    private javax.swing.JComboBox<String> xsatbrg;
    // End of variables declaration//GEN-END:variables
}
