/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum.pkg11;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.String;
import static javafx.beans.binding.Bindings.select;


public class FormFaktur extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    Statement stm;
    DefaultTableModel tabmod;

    /**
     * Creates new form FormFaktur
     */
    public FormFaktur() throws SQLException {
        initComponents();
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan2", "root", "");
        
        stm = conn.createStatement();
        grandTotFak.setText(""+0);
        ppnFak.setText(""+0);
        diskonFak.setText(""+0);
        Total.setText(""+0);
          tampilTempor();

    }
    private void tampilTempor() throws SQLException{
         DefaultTableModel tabmod = new DefaultTableModel();
    tabmod.addColumn("Kode");
    tabmod.addColumn("Nama");
    tabmod.addColumn("Satuan");
    tabmod.addColumn("Harga");
    tabmod.addColumn("Jumlah");
    tabmod.addColumn("Total");
    jTable1.setModel(tabmod);
    String query4="select * from temporary";
    ResultSet rs=stm.executeQuery(query4);
     while(rs.next()){
         tabmod.addRow(new Object[]{
             rs.getString("kode"), 
             rs.getString("namabarang"), 
             rs.getString("satuan"), 
             rs.getInt("harga"),
             rs.getInt("jumlah"), 
             rs.getInt("total_jual")});

         
     }
        
    }
    private void HitungTotal(){
        try {
            rs=stm.executeQuery("select sum(total_jual) as total from temporary");
            while(rs.next()){
            grandTotFak.setText(rs.getString("total"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormFaktur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        xtglFaktur = new javax.swing.JTextField();
        xnofak = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xKodepel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xNamapel = new javax.swing.JTextField();
        xKotapel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        xkdBrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        xSatuan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        xJmlbrg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        xHrgbrg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        xTotalbrg = new javax.swing.JTextField();
        xNamaBrg = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        grandTotFak = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        diskonFak = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ppnFak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Faktur Penjualan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        xtglFaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtglFakturActionPerformed(evt);
            }
        });

        xnofak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xnofakActionPerformed(evt);
            }
        });

        jLabel2.setText("Tgl Faktur");

        jLabel3.setText("No Faktur");

        xKodepel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xKodepelKeyPressed(evt);
            }
        });

        jLabel4.setText("Kode pelanggan");

        jLabel5.setText("Nama Pelanggan");

        xNamapel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xNamapelFocusGained(evt);
            }
        });

        xKotapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xKotapelActionPerformed(evt);
            }
        });

        jLabel6.setText("Kota");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(xtglFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(xnofak, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xKodepel)
                    .addComponent(xNamapel)
                    .addComponent(xKotapel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xtglFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(xKodepel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xnofak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(xNamapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xKotapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel7.setText("kode brg");

        xkdBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xkdBrgActionPerformed(evt);
            }
        });
        xkdBrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xkdBrgKeyPressed(evt);
            }
        });

        jLabel8.setText("nama brg");

        xSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xSatuanActionPerformed(evt);
            }
        });

        jLabel9.setText("satuan");

        jLabel10.setText("jumlah");

        xJmlbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xJmlbrgActionPerformed(evt);
            }
        });
        xJmlbrg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xJmlbrgKeyReleased(evt);
            }
        });

        jLabel11.setText("harga");

        xHrgbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xHrgbrgActionPerformed(evt);
            }
        });

        jLabel12.setText("total");

        xNamaBrg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xNamaBrgFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xkdBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(xNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(xSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xJmlbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xHrgbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xTotalbrg, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xkdBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xJmlbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xHrgbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xTotalbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xNamaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("New");

        jButton2.setText("Process");

        jButton3.setText("Delete");

        jButton4.setText("Exit");

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel13.setText("Grand Total");

        jLabel14.setText("ppn 10%");

        jLabel15.setText("Diskon");

        jLabel16.setText("Total");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Total)
                    .addComponent(diskonFak)
                    .addComponent(grandTotFak)
                    .addComponent(ppnFak, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(grandTotFak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ppnFak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskonFak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xtglFakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtglFakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xtglFakturActionPerformed

    private void xKotapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xKotapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xKotapelActionPerformed

    private void xSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xSatuanActionPerformed

    private void xkdBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xkdBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xkdBrgActionPerformed

    private void xKodepelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xKodepelKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            xNamapel.requestFocus();
        }
    }//GEN-LAST:event_xKodepelKeyPressed

    private void xNamapelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xNamapelFocusGained
        if (xKodepel.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Kode Pelanggan Masih Kosong!");
            xKodepel.requestFocus();
        } else {
            String query = "SELECT * FROM faktur_plgn WHERE kd_plgn = '" + xKodepel.getText() + "'";

            try {
                rs = stm.executeQuery(query);
                while (rs.next()) {
                    xNamapel.setText(rs.getString("nama"));
                    xKotapel.setText(rs.getString("kota"));
                    xkdBrg.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormFaktur.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_xNamapelFocusGained

    private void xkdBrgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xkdBrgKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            xNamaBrg.requestFocus();
        }
    }//GEN-LAST:event_xkdBrgKeyPressed

    private void xNamaBrgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xNamaBrgFocusGained
            if(xkdBrg.getText().equals("")){
        JOptionPane.showMessageDialog(rootPane,"Kode Barang Masih Kosong!");
        xkdBrg.requestFocus();
    }
    else{
        String query2 = "SELECT * FROM faktur_brng WHERE kd_brng = '" + xkdBrg.getText() + "'";

        try {
            rs=stm.executeQuery(query2);
            if (rs.next()){
                xNamaBrg.setText(rs.getString("nama"));
                xSatuan.setText(rs.getString("satuan"));
                xJmlbrg.setText(String.valueOf(rs.getInt("jumlah")));
                xHrgbrg.setText(String.valueOf(rs.getInt("harga")));
                xJmlbrg.requestFocus();
            } else {
                JOptionPane.showMessageDialog(rootPane,"Barang dengan Kode tersebut tidak ditemukan!");
                xkdBrg.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormFaktur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_xNamaBrgFocusGained

    private void xJmlbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xJmlbrgActionPerformed

    }//GEN-LAST:event_xJmlbrgActionPerformed

    private void xHrgbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xHrgbrgActionPerformed

    }//GEN-LAST:event_xHrgbrgActionPerformed

    private void xJmlbrgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xJmlbrgKeyReleased
      if(xJmlbrg.getText().equals("")){
          xJmlbrg.setText(""+0);
      }
      if(evt.getKeyCode()==evt.VK_ENTER){
      int jmlBrng =Integer.parseInt(xJmlbrg.getText().toString());
      int hrgBrng =Integer.parseInt(xHrgbrg.getText().toString());
      int totale  =(jmlBrng*hrgBrng);
      xTotalbrg.setText(Integer.toString(totale));
      Calendar cal=Calendar.getInstance();
      SimpleDateFormat contoh2 = new SimpleDateFormat("yyyy-MM-dd");
      String tanggal2 =contoh2.format(cal.getTime());
      xtglFaktur.setText(tanggal2);
      
     String query3 = "INSERT INTO temporary (kode, namabarang, satuan, jumlah, harga, total_jual, kd_plgn, no_fak, tgl_fak, diskon_fak, total_fak, nama_plgn, kota_plgn) VALUES ("
    + xkdBrg.getText() + ", '"
    + xNamaBrg.getText() + "', '"
    + xSatuan.getText() + "', "
    + Integer.parseInt(xJmlbrg.getText()) + ", "
    + Integer.parseInt(xHrgbrg.getText()) + ", "
    + Integer.parseInt(xTotalbrg.getText()) + ", "
    + Integer.parseInt(xKodepel.getText()) + ", "
    + Integer.parseInt(xnofak.getText()) + ", '"
    + tanggal2 + "', "
    + Integer.parseInt(diskonFak.getText()) + ", "
    + Integer.parseInt(Total.getText()) + ", '"
    + xNamapel.getText() + "', '"
    + xKotapel.getText() + "'"
    + ")";
        try {
            Statement stm=conn.createStatement();
            stm.executeUpdate(query3);
              tampilTempor();
              HitungTotal();
        } catch (SQLException ex) {
            Logger.getLogger(FormFaktur.class.getName()).log(Level.SEVERE, null, ex);
        }

      }
      
    }//GEN-LAST:event_xJmlbrgKeyReleased

    private void xnofakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xnofakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xnofakActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFaktur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormFaktur().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormFaktur.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Total;
    private javax.swing.JTextField diskonFak;
    private javax.swing.JTextField grandTotFak;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ppnFak;
    private javax.swing.JTextField xHrgbrg;
    private javax.swing.JTextField xJmlbrg;
    private javax.swing.JTextField xKodepel;
    private javax.swing.JTextField xKotapel;
    private javax.swing.JTextField xNamaBrg;
    private javax.swing.JTextField xNamapel;
    private javax.swing.JTextField xSatuan;
    private javax.swing.JTextField xTotalbrg;
    private javax.swing.JTextField xkdBrg;
    private javax.swing.JTextField xnofak;
    private javax.swing.JTextField xtglFaktur;
    // End of variables declaration//GEN-END:variables

  
}
